name: Automated Push to Selfii

on:
  # limit workflow runs to PRs only
  pull_request:
    # limit workflow runs to closed event only
    types: [closed]
    # NOTE: the closed event also fired once the PR is MERGED!

jobs:
  call-push-workflow:
    # only run this job if the target branch of this PR is `master` and the repo owner is WikiTeq
    # and ignore completely on merges
    if: |
      github.event.pull_request.merged != true &&
      github.repository_owner == 'wikiteq' &&
      github.event.pull_request.base.ref == 'master' &&
      !contains(github.event.pull_request.labels.*.name, 'do not sync')
    uses: wikiteq/selfiie-workflows/.github/workflows/automated-push-pr.yml@master
    with:
      target_org: SelfiieCorporation
      target_base_branch: main
      pat_username: WikiteqMachine
    secrets:
      pat_token: ${{ secrets.WIKITEQMACHINE }}
