name: Automated Warning for PRs

on:
  # limit workflow runs to PRs only
  pull_request:
    # limit workflow runs to closed event only
    types: [opened]

jobs:
  call-warning-workflow:
    # only run this job if the target branch of this PR is `master` and the repo owner is WikiTeq
    if: |
      github.repository_owner == 'wikiteq' &&
      github.event.pull_request.base.ref == 'master'
    uses: wikiteq/selfiie-workflows/.github/workflows/automated-warning-pr.yml@master
